server {
    listen       80;
    listen       443 ssl;
    ssl_certificate      /etc/nginx/ssl/git.crt;
    ssl_certificate_key  /etc/nginx/ssl/git.key;
    server_name  localhost;
    root /srv/git;
    location ~ (/.*\.git)(/.*)?$ {
        include fastcgi_params;
        fastcgi_param SCRIPT_FILENAME   /usr/lib/git-core/git-http-backend;
        fastcgi_param GIT_PROJECT_ROOT  /srv/git;
        fastcgi_param GIT_HTTP_EXPORT_ALL "";
        fastcgi_param PATH_INFO         $2;
        fastcgi_pass                    unix:/var/run/fcgiwrap.socket;
    }
}

